'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.products': 'Products',
    'nav.services': 'Services',
    'nav.projects': 'Completed Projects',
    'nav.gallery': 'Gallery',
    'nav.quotation': 'Quotation',
    'nav.contact': 'Contact Us',
    'nav.admin': 'Admin Dashboard',
    'nav.tools': 'Smart Tools',
    'nav.sourcing': 'Supply & Partners',
    'nav.company': 'Company',
    'nav.estimator': 'Cost Estimator',
    'nav.compare': 'Material Compare',
    'nav.ai-assistant': 'AI Assistant',
    'nav.rfq': 'RFQ Portal',
    'nav.marketplace': 'Marketplace',
    'nav.partners': 'Partners Network',
    'nav.seller': 'Seller Portal',
    'nav.estimator.desc': 'AI-powered house cost calculator',
    'nav.compare.desc': 'Compare steel & cement brands',
    'nav.ai-assistant.desc': 'Expert engineering helper chatbot',
    'nav.rfq.desc': 'Request custom bulk quotations',
    'nav.marketplace.desc': 'Order building materials online',
    'nav.partners.desc': 'Our dealership & engineer network',
    'nav.seller.desc': 'List materials & fulfill orders',
    'nav.about.desc': 'Our timeline, team, and depots',
    'nav.contact.desc': 'Get in touch with wholesale desks',
    'nav.projects.desc': 'Gallery of our structural builds',

    // Hero
    'hero.title': 'Premium Building Materials & Infrastructure Distribution',
    'hero.title_part1': 'Building the Future',
    'hero.title_part2': 'One Material at a Time',
    'hero.subtitle': 'Authorized wholesale supplier of top-tier cement brands, high-tensile TMT steel, washed river sand, aggregates, and hardware tools.',
    'hero.cta.portal': 'View Catalog',
    'hero.cta.contact': 'Request Quote',
    'hero.scroll_indicator': 'Scroll to Explore Story',
    'hero.award': 'Award-Winning Sourcing Solutions',

    // Stats
    'stats.clients': 'Dealer Network',
    'stats.trips': 'Deliveries Fulfilled',
    'stats.meals': 'Projects Supplied',
    'stats.materials': 'Tons Distributed',

    // Company Story Timeline
    'story.sub': 'Chronicle of Growth',
    'story.title': 'Our 3D Construction Timeline',
    'story.desc': 'See how we built a regional distribution network from the foundation up.',
    'story.m1.title': 'Local Sourcing Bed',
    'story.m1.desc': 'Began regional river sand and aggregate supply with a modest fleet of three dumpers.',
    'story.m2.title': 'Heavy Fleet Expansion',
    'story.m2.desc': 'Acquired 15 high-capacity transit tippers and completed ISO 9001 certified warehouses.',
    'story.m3.title': 'Wholesale Dealerships',
    'story.m3.desc': 'Signed direct dealership tie-ups with UltraTech Cement, JSW, and Tata Tiscon steel.',
    'story.m4.title': 'Next-Gen Marketplace',
    'story.m4.desc': 'Launched AI-powered construction estimators and digital marketplace sourcing portal.',

    // Product Showcase
    'prod.sub': 'Factory Direct',
    'prod.title': 'Product Gallery',
    'prod.desc': 'Hover to highlight 3D models and explore live wholesale rates.',
    'prod.status': '🟢 Live Pricing Active',
    'prod.cert_desc': 'Certified premium standard grading with official lab test checks and guaranteed structural strength values.',
    'prod.specs_label': 'Specifications',
    'prod.rate_label': 'Wholesale Net Price',
    'prod.btn_market': 'Go to Marketplace',
    'prod.btn_compare': '⚖️ Compare Materials',
    'prod.p1.name': 'UltraTech OPC 53 Cement',
    'prod.p1.desc': 'Highest compressive strength cement for heavy load pillars & foundations.',
    'prod.p1.spec': '53 MPa compressive strength',
    'prod.p1.rate': '₹380 - ₹430 / bag',
    'prod.p2.name': 'Tata Tiscon Fe 550D Steel',
    'prod.p2.desc': 'Seismic resistant TMT structural rebar bars with high elasticity ribs.',
    'prod.p2.spec': 'Fe 550D High ductility',
    'prod.p2.rate': '₹64,000 - ₹68,000 / MT',
    'prod.p3.name': 'Girna washed River Sand',
    'prod.p3.desc': 'Double-washed silt-free coarse sand for premium plastering & RCC matrix.',
    'prod.p3.spec': '<1% silt content',
    'prod.p3.rate': '₹6,500 / Brass',
    'prod.p4.name': 'Double Crushed Aggregates',
    'prod.p4.desc': 'High-density basalt stone aggregates in standard 10mm & 20mm aggregate sizes.',
    'prod.p4.spec': '100% hard basalt rock',
    'prod.p4.rate': '₹4,000 - ₹4,200 / Brass',
    'prod.p5.name': 'Astral CPVC / PVC Pipes',
    'prod.p5.desc': 'Certified industrial strength Cpvc and PVC pipes for hot/cold water plumbing.',
    'prod.p5.spec': 'SDR 11 & SWR certified',
    'prod.p5.rate': '₹350 / Meter',

    // Logistics Supply Chain
    'log.sub': 'Fulfillment Route',
    'log.title': 'Our Supply Chain Journey',
    'log.desc': 'Watch how materials route from our sourcing depots directly to your construction sites.',
    'log.s1.title': 'Factory Sourcing',
    'log.s1.desc': 'Cement and TMT steel are loaded directly from manufacturer kilns and mills.',
    'log.s1.detail': 'UltraTech & Tata Tie-ups',
    'log.s2.title': 'Weighbridge Check',
    'log.s2.desc': 'Dumpers and trucks pass rigorous weight checks to guarantee exact quantities.',
    'log.s2.detail': 'Zero Silt / Pure Matrix',
    'log.s3.title': 'Transit Logistics',
    'log.s3.desc': 'Real-time GPS coordinates track carrier dumpers moving across Maharashtra roads.',
    'log.s3.detail': '24/7 Dumper Fleet',
    'log.s4.title': 'Site Drop-off',
    'log.s4.desc': 'Materials are unloaded at the builder\'s project site with digital invoices.',
    'log.s4.detail': 'Phased Mobilization',

    // Why Choose Us
    'wcu.sub': 'Our Standards',
    'wcu.title': 'Why Builders Trust Us',
    'wcu.subtitle': 'Securing premium construction supplies with verified certifications and logistical speed.',
    'wcu.quality.title': 'Certified Quality',
    'wcu.quality.desc': 'OPC/PPC cement and FE 550D TMT steel rod batches pass rigorous laboratory test checks before delivery.',
    'wcu.fleet.title': 'Logistical Power',
    'wcu.fleet.desc': 'Our own logistics transit fleet of dumpers and trucks guarantees 24/7 on-site delivery coordinates.',
    'wcu.support.title': 'Project Desk Support',
    'wcu.support.desc': 'Dedicated account handlers to schedule phased drop-offs for commercial housing complexes.',
    'wcu.i1.title': 'Certified Quality',
    'wcu.i1.desc': 'All materials pass laboratory test checks. Sourced strictly from ISI-certified cement kilns and high-tensile steel mills.',
    'wcu.i2.title': 'Logistical Power',
    'wcu.i2.desc': 'Own fleet of heavy dumper trucks provides 24/7 delivery. Guaranteed on-time coordination across Jalgaon district.',
    'wcu.i3.title': 'Wholesale Discount',
    'wcu.i3.desc': 'Factory-direct contracts and zero middlemen markup allow us to supply builders with bulk discounts.',
    'wcu.i4.title': 'Large Inventory',
    'wcu.i4.desc': 'Moisture-free massive warehouses ensure we keep high volumes of cement, steel, and sand in stock.',
    'wcu.i5.title': 'Expert Sourcing Support',
    'wcu.i5.desc': 'Dedicated accounts manager to draft custom phased BOQs and coordinate drop-off slots.',
    'wcu.i6.title': 'Digital Sourcing Tools',
    'wcu.i6.desc': 'Interactive 3D cost calculators, instant comparisons, and digital sitemap analytics in one portal.',

    // Before/After Slider
    'proj.sub': 'Project Showcase',
    'proj.title': 'Before & After Comparisons',
    'proj.desc': 'Slide the handle to view the transformation from raw excavation sites to fully completed structural layouts.',
    'proj.before.label': 'Stage 1: Foundation',
    'proj.before.title': 'Excavation & Footing prep',
    'proj.before.desc': 'Slab layout at Girad campus yard',
    'proj.after.label': 'Stage 4: Completed Structural layout',
    'proj.after.title': 'Modern Materials Complex',
    'proj.after.desc': 'ISO 9001 certified warehouse stockyards',
    'proj.s1.title': 'Structural Safety',
    'proj.s1.sub': 'Tested materials integrity',
    'proj.s2.title': 'Building Sites',
    'proj.s2.sub': 'Supplied in Jalgaon region',
    'proj.s3.title': 'Carrier Drops',
    'proj.s3.sub': 'Continuous logistics dispatches',
    'proj.s4.title': 'Logistics Failures',
    'proj.s4.sub': 'Guaranteed drop coordination',

    // Testimonials
    'test.sub': 'Contractor Testimonials',
    'test.title': 'Client Endorsements',
    'test.t1.text': 'For our recent residential township project, Jay Shree Ram supplied over 5000 brass of river sand on an extremely tight timeline. Their dumpers were on site like clockwork.',
    'test.t1.role': 'Project Director, RMD Developers',
    'test.t1.project': 'Girad Township Phase-I',
    'test.t2.text': 'Jay Shree Ram is our sole supplier for high-strength cement and TMT steel rebar projects. Their wholesale dealership rates and coordinated drop schedules are outstanding.',
    'test.t2.role': 'MD, Jalgaon Buildcon',
    'test.t2.project': 'NH-6 Infrastructure bypass',
    'test.t3.text': 'We order structural TMT steel and bulk OPC cement from Jay Shree Ram. Quality reports are provided with every batch, and their rates are highly competitive.',
    'test.t3.role': 'Contractor, PWD Infrastructure',
    'test.t3.project': 'PWD Government School Project',

    // Contact
    'contact.sub': 'Get in Touch',
    'contact.title': 'Start Sourcing Materials',
    'contact.desc': 'Fill out the form below or locate our central warehouse depots in Jalgaon District.',
    'contact.desk_title': 'Corporate Sourcing Desk',
    'contact.desk_desc': 'Connect with our commercial dispatch officers. We schedule bulk cement and TMT steel dispatches within 24 hours.',
    'contact.loc_label': 'Main Stockyard',
    'contact.loc_address': 'Girad, Taluka Bhadgaon, Jalgaon, MH',
    'contact.phone_label': 'Wholesale Support Desk',
    'contact.email_label': 'Corporate Inquiries',
    'contact.globe_active': '🌍 Interactive Globe active',
    'contact.globe_desc': 'The spinning 3D wireframe globe in the background represents our region-wide heavy carrier logistics reach.',

    // Inquiry Form
    'inq.title': 'Request Material Quotation',
    'inq.subtitle': 'Fill out the order specifications below and our pricing desk will coordinate rates in 2 hours.',
    'inq.name': 'Your Name / Company',
    'inq.email': 'Email Address',
    'inq.phone': 'Phone Number',
    'inq.division': 'Select Category',
    'inq.div.hotel': 'Cement & Steel Rebars',
    'inq.div.sand': 'Sand & Aggregate Cargo',
    'inq.div.materials': 'Construction & Plaster Supplies',
    'inq.message': 'Required Quantity & Delivery Site Address',
    'inq.submit': 'Submit Quote Request',
    'inq.sending': 'Processing...',
    'inq.success': 'Thank you! Your quotation inquiry has been registered. Our pricing team will call you shortly.',
    'inq.error': '⚠️ Something went wrong. Please check details and try again.',

    // Chatbot
    'chat.welcome': 'Namaste! Welcome to Jay Shree Ram. I am your materials helper. How can I assist you with construction supplies today?',
    'chat.opt.hotel': 'Request material price list',
    'chat.opt.sand': 'Get sand delivery quote',
    'chat.opt.materials': 'Inquire bulk cement/steel',
    'chat.opt.support': 'Contact logistics dispatcher',

    // About Us
    'about.story.title': 'Heritage of Structural Integrity',
    'about.story.desc': 'Founded by Mr. Bhaiyya Patil, Jay Shree Ram has evolved from a local cargo transit operator to a leading regional construction materials distributor. We operate high-capacity storage warehouses supplying major developers.',
    'about.vision': 'Our Vision',
    'about.vision.desc': 'To be the most reliable, scale-driven building materials partner for infrastructure and housing projects in Maharashtra.',
    'about.mission': 'Our Mission',
    'about.mission.desc': 'Providing certified, high-durability concrete materials, steel rebars, and aggregates on-time, every time, supporting robust structures.',
    'about.cert': 'Engineering Accreditations & Standards',

    // Contact General
    'contact.info': 'Central Corporate Head Office',
    'contact.phone': 'Wholesale Dispatch Desk',
    'contact.email': 'Corporate Inquiries',
    'contact.address': 'Girad, Taluka Bhadgaon, Dist Jalgaon, Maharashtra, India',
    'contact.whatsapp': 'Chat with Sales Desk',
  },
  hi: {
    // Nav
    'nav.home': 'मुख्य पृष्ठ',
    'nav.about': 'हमारे बारे में',
    'nav.products': 'उत्पाद',
    'nav.services': 'सेवाएं',
    'nav.projects': 'पूर्ण परियोजनाएं',
    'nav.gallery': 'गैलरी',
    'nav.quotation': 'कोटेशन',
    'nav.contact': 'संपर्क करें',
    'nav.admin': 'डैशबोर्ड',
    'nav.tools': 'स्मार्ट टूल्स',
    'nav.sourcing': 'आपूर्ति और भागीदार',
    'nav.company': 'कंपनी',
    'nav.estimator': 'लागत कैलकुलेटर',
    'nav.compare': 'सामग्री तुलना',
    'nav.ai-assistant': 'एआई सहायक',
    'nav.rfq': 'आरएफक्यू पोर्टल',
    'nav.marketplace': 'मार्केटप्लेस',
    'nav.partners': 'भागीदार नेटवर्क',
    'nav.seller': 'विक्रेता पोर्टल',
    'nav.estimator.desc': 'घर निर्माण की लागत की गणना करें',
    'nav.compare.desc': 'सीमेंट और स्टील ब्रांड्स की तुलना करें',
    'nav.ai-assistant.desc': 'एआई निर्माण विशेषज्ञ से सलाह लें',
    'nav.rfq.desc': 'थोक ऑर्डर के लिए कोटेशन मांगें',
    'nav.marketplace.desc': 'निर्माण सामग्री ऑनलाइन ऑर्डर करें',
    'nav.partners.desc': 'अधिकृत डीलर और इंजीनियर नेटवर्क',
    'nav.seller.desc': 'वितरक डैशबोर्ड और आर्डर प्रबंधन',
    'nav.about.desc': 'हमारा इतिहास, बेड़ा और गोदाम',
    'nav.contact.desc': 'हमारे थोक आपूर्ति डेस्क से जुड़ें',
    'nav.projects.desc': 'हमारी पूर्ण परियोजनाओं की गैलरी',

    // Hero
    'hero.title': 'प्रीमियम भवन निर्माण सामग्री और बुनियादी ढांचा वितरण',
    'hero.title_part1': 'भविष्य का निर्माण',
    'hero.title_part2': 'एक समय में एक सामग्री',
    'hero.subtitle': 'शीर्ष सीमेंट ब्रांडों, उच्च-शक्ति टीएमटी स्टील, धुली हुई नदी की रेत, गिट्टी और हार्डवेयर उपकरणों के अधिकृत थोक आपूर्तिकर्ता।',
    'hero.cta.portal': 'कैटलॉग देखें',
    'hero.cta.contact': 'कोटेशन का अनुरोध करें',
    'hero.scroll_indicator': 'कहानी का पता लगाने के लिए स्क्रॉल करें',
    'hero.award': 'पुरस्कार विजेता सोर्सिंग समाधान',

    // Stats
    'stats.clients': 'डीलर नेटवर्क',
    'stats.trips': 'पूरी हुई डिलीवरी',
    'stats.meals': 'आपूर्ति की गई परियोजनाएं',
    'stats.materials': 'टन वितरित',

    // Company Story Timeline
    'story.sub': 'विकास का इतिहास',
    'story.title': 'हमारा 3D निर्माण समयरेखा',
    'story.desc': 'देखें कि हमने कैसे नींव से शुरू कर एक मजबूत क्षेत्रीय वितरण नेटवर्क खड़ा किया।',
    'story.m1.title': 'स्थानीय सोर्सिंग आधार',
    'story.m1.desc': 'तीन डंपरों के छोटे बेड़े के साथ क्षेत्रीय नदी रेत और गिट्टी आपूर्ति शुरू की।',
    'story.m2.title': 'भारी वाहन बेड़े का विस्तार',
    'story.m2.desc': '15 उच्च क्षमता वाले ट्रांजिट टिपर खरीदे और आईएसओ 9001 प्रमाणित गोदामों का निर्माण पूरा किया।',
    'story.m3.title': 'थोक डीलरशिप',
    'story.m3.desc': 'अल्ट्राटेक सीमेंट, जेएसडब्ल्यू और टाटा टिस्कन स्टील के साथ सीधे डीलरशिप समझौते किए।',
    'story.m4.title': 'अगली पीढ़ी का मार्केटप्लेस',
    'story.m4.desc': 'एआई-संचालित निर्माण लागत अनुमानक और डिजिटल मार्केटप्लेस सोर्सिंग पोर्टल लॉन्च किया।',

    // Product Showcase
    'prod.sub': 'सीधे कारखाने से',
    'prod.title': 'उत्पाद गैलरी',
    'prod.desc': '3D मॉडल देखने और थोक दरों का पता लगाने के लिए माउस घुमाएं।',
    'prod.status': '🟢 लाइव मूल्य निर्धारण सक्रिय',
    'prod.cert_desc': 'आधिकारिक प्रयोगशाला परीक्षण जांच और गारंटीकृत संरचनात्मक शक्ति के साथ प्रमाणित प्रीमियम मानक उत्पाद।',
    'prod.specs_label': 'तकनीकी विवरण',
    'prod.rate_label': 'थोक शुद्ध मूल्य',
    'prod.btn_market': 'मार्केटप्लेस पर जाएं',
    'prod.btn_compare': 'सामग्री की तुलना करें',
    'prod.p1.name': 'अल्ट्राटेक ओपीसी 53 सीमेंट',
    'prod.p1.desc': 'भारी खंभों और नींव के लिए उच्चतम संपीड़न शक्ति वाला सीमेंट।',
    'prod.p1.spec': '53 MPa संपीड़न शक्ति',
    'prod.p1.rate': '₹380 - ₹430 / बोरी',
    'prod.p2.name': 'टाटा टिस्कन Fe 550D स्टील',
    'prod.p2.desc': 'उच्च लचीलेपन वाले भूकंप प्रतिरोधी टीएमटी संरचनात्मक सरिये।',
    'prod.p2.spec': 'Fe 550D उच्च लचीलापन',
    'prod.p2.rate': '₹64,000 - ₹68,000 / मीट्रिक टन',
    'prod.p3.name': 'गिरना नदी की धुली रेत',
    'prod.p3.desc': 'प्लास्टर और आरसीसी निर्माण के लिए कीचड़ मुक्त दो बार धुली रेत।',
    'prod.p3.spec': '<1% गाद की मात्रा',
    'prod.p3.rate': '₹6,500 / ब्रास',
    'prod.p4.name': 'क्रश की गई गिट्टी (खड़ी)',
    'prod.p4.desc': 'मानक 10 मिमी और 20 मिमी आकार में उच्च घनत्व वाली बेसाल्ट पत्थर की गिट्टी।',
    'prod.p4.spec': '100% ठोस बेसाल्ट पत्थर',
    'prod.p4.rate': '₹4,000 - ₹4,200 / ब्रास',
    'prod.p5.name': 'एस्ट्रल सीपीवीसी / पीवीसी पाइप',
    'prod.p5.desc': 'गर्म/ठंडे पानी की प्लंबिंग के लिए प्रमाणित औद्योगिक शक्ति के सीपीवीसी और पीवीसी पाइप।',
    'prod.p5.spec': 'SDR 11 और SWR प्रमाणित',
    'prod.p5.rate': '₹350 / मीटर',

    // Logistics Supply Chain
    'log.sub': 'वितरण मार्ग',
    'log.title': 'हमारी आपूर्ति श्रृंखला यात्रा',
    'log.desc': 'देखें कि हमारे सोर्सिंग डिपो से निर्माण सामग्री सीधे आपकी साइट तक कैसे पहुंचती है।',
    'log.s1.title': 'फैक्ट्री सोर्सिंग',
    'log.s1.desc': 'सीमेंट और स्टील सीधे निर्माता की भट्ठियों और मिलों से लोड किए जाते हैं।',
    'log.s1.detail': 'अल्ट्राटेक और टाटा साझेदारी',
    'log.s2.title': 'वेब्रिज (धर्मकांटा) जांच',
    'log.s2.desc': 'सटीक मात्रा सुनिश्चित करने के लिए डंपर और ट्रक कड़े वजन जांच से गुजरते हैं।',
    'log.s2.detail': 'शून्य गाद / शुद्ध सामग्री',
    'log.s3.title': 'ट्रांजिट लॉजिस्टिक्स',
    'log.s3.desc': 'महाराष्ट्र की सड़कों पर चलते डंपरों की वास्तविक समय में जीपीएस ट्रैकिंग।',
    'log.s3.detail': '24/7 डंपर बेड़ा',
    'log.s4.title': 'साइट पर डिलीवरी',
    'log.s4.desc': 'डिजिटल चालान के साथ सामग्री बिल्डर की परियोजना साइट पर अनलोड की जाती है।',
    'log.s4.detail': 'चरणबद्ध मोबिलाइजेशन',

    // Why Choose Us
    'wcu.sub': 'हमारे मानक',
    'wcu.title': 'बिल्डर्स हम पर भरोसा क्यों करते हैं',
    'wcu.subtitle': 'प्रमाणित प्रमाणपत्रों और तार्किक गति के साथ प्रीमियम निर्माण आपूर्ति सुरक्षित करना।',
    'wcu.quality.title': 'प्रमाणित गुणवत्ता',
    'wcu.quality.desc': 'ओपीसी/पीपीसी सीमेंट और Fe 550D टीएमटी स्टील सरिये डिलीवरी से पहले सख्त प्रयोगशाला परीक्षणों से गुजरते हैं।',
    'wcu.fleet.title': 'लॉजिस्टिक शक्ति',
    'wcu.fleet.desc': 'डंपरों और ट्रकों का हमारा अपना बेड़ा 24/7 ऑन-साइट डिलीवरी की गारंटी देता है।',
    'wcu.support.title': 'परियोजना डेस्क समर्थन',
    'wcu.support.desc': 'व्यावसायिक आवास परिसरों के लिए चरणबद्ध डिलीवरी शेड्यूल करने के लिए समर्पित खाता प्रबंधक।',
    'wcu.i1.title': 'प्रमाणित गुणवत्ता',
    'wcu.i1.desc': 'सभी सामग्रियां प्रयोगशाला परीक्षणों से गुजरती हैं। विशेष रूप से आईएसआई-प्रमाणित कारखानों से सोर्स की जाती हैं।',
    'wcu.i2.title': 'लॉजिस्टिक ताकत',
    'wcu.i2.desc': 'डंपर ट्रकों का हमारा अपना बेड़ा 24/7 डिलीवरी प्रदान करता है। पूरे जलगांव जिले में समय पर डिलीवरी की गारंटी।',
    'wcu.i3.title': 'थोक छूट',
    'wcu.i3.desc': 'सीधे कारखाने के अनुबंधों और बिना किसी बिचौलिए के मार्जिन के कारण हम थोक छूट प्रदान करते हैं।',
    'wcu.i4.title': 'बड़ा स्टॉक',
    'wcu.i4.desc': 'नमी-मुक्त विशाल गोदाम सुनिश्चित करते हैं कि हमारे पास सीमेंट, स्टील और रेत भारी मात्रा में उपलब्ध हो।',
    'wcu.i5.title': 'विशेषज्ञ सोर्सिंग सहायता',
    'wcu.i5.desc': 'चरणबद्ध सामग्री योजना (BOQ) तैयार करने और डिलीवरी स्लॉट समन्वय के लिए समर्पित खाता प्रबंधक।',
    'wcu.i6.title': 'डिजिटल सोर्सिंग टूल्स',
    'wcu.i6.desc': 'एक ही पोर्टल में इंटरैक्टिव 3D लागत कैलकुलेटर, तत्काल तुलना और डिजिटल साइट विश्लेषण।',

    // Before/After Slider
    'proj.sub': 'परियोजना प्रदर्शन',
    'proj.title': 'पहले और बाद की तुलना',
    'proj.desc': 'खुदाई वाली कच्ची साइटों से लेकर तैयार इमारतों तक के बदलाव को देखने के लिए हैंडल को खिसकाएं।',
    'proj.before.label': 'चरण 1: नींव',
    'proj.before.title': 'खुदाई और बेस तैयारी',
    'proj.before.desc': 'गिरड परिसर यार्ड में स्लैब लेआउट काम',
    'proj.after.label': 'चरण 4: पूर्ण ढांचा',
    'proj.after.title': 'आधुनिक सामग्री परिसर',
    'proj.after.desc': 'आईएसओ 9001 प्रमाणित गोदाम स्टॉकयार्ड',
    'proj.s1.title': 'संरचनात्मक सुरक्षा',
    'proj.s1.sub': 'परीक्षणित सामग्री अखंडता',
    'proj.s2.title': 'निर्माण साइटें',
    'proj.s2.sub': 'जलगांव क्षेत्र में आपूर्ति की गई',
    'proj.s3.title': 'कैरियर डिलीवरी',
    'proj.s3.sub': 'निरंतर लॉजिस्टिक्स डिस्पैच',
    'proj.s4.title': 'लॉजिस्टिक्स असफलता',
    'proj.s4.sub': 'शून्य असफलता, समय पर डिलीवरी',

    // Testimonials
    'test.sub': 'ठेकेदार प्रशंसापत्र',
    'test.title': 'ग्राहकों की प्रतिक्रिया',
    'test.t1.text': 'हमारे हालिया आवासीय टाउनशिप प्रोजेक्ट के लिए, जय श्री राम ने बेहद कम समय सीमा में 5000 ब्रास से अधिक नदी की रेत की आपूर्ति की। उनके डंपर समय पर साइट पर थे।',
    'test.t1.role': 'परियोजना निदेशक, आरएमडी डेवलपर्स',
    'test.t1.project': 'गिरड टाउनशिप चरण-I',
    'test.t2.text': 'जय श्री राम उच्च शक्ति वाले सीमेंट और टीएमटी स्टील सरियों के लिए हमारे एकमात्र आपूर्तिकर्ता हैं। उनके थोक दर और डिलीवरी शेड्यूल बेहतरीन हैं।',
    'test.t2.role': 'एमडी, जलगांव बिल्डकॉन',
    'test.t2.project': 'NH-6 इंफ्रास्ट्रक्चर बाईपास',
    'test.t3.text': 'हम जय श्री राम से स्ट्रक्चरल टीएमटी स्टील और थोक ओपीसी सीमेंट मंगवाते हैं। प्रत्येक बैच के साथ गुणवत्ता रिपोर्ट प्रदान की जाती है।',
    'test.t3.role': 'ठेकेदार, पीडब्ल्यूडी इंफ्रास्ट्रक्चर',
    'test.t3.project': 'पीडब्ल्यूडी सरकारी स्कूल परियोजना',

    // Contact
    'contact.sub': 'संपर्क करें',
    'contact.title': 'सामग्री सोर्सिंग शुरू करें',
    'contact.desc': 'नीचे दिया गया फॉर्म भरें या जलगांव जिले में हमारे केंद्रीय गोदामों का पता लगाएं।',
    'contact.desk_title': 'कॉर्पोरेट सोर्सिंग डेस्क',
    'contact.desk_desc': 'हमारे वाणिज्यिक डिस्पैच अधिकारियों से जुड़ें। हम 24 घंटे के भीतर सीमेंट और स्टील डिस्पैच की व्यवस्था करते हैं।',
    'contact.loc_label': 'मुख्य स्टॉकयार्ड',
    'contact.loc_address': 'गिरड, तालुका भड़गांव, जलगांव, महाराष्ट्र',
    'contact.phone_label': 'थोक सहायता डेस्क',
    'contact.email_label': 'कॉर्पोरेट पूछताछ',
    'contact.globe_active': 'इंटरैक्टिव ग्लोब सक्रिय',
    'contact.globe_desc': 'पृष्ठभूमि में घूमता हुआ 3D ग्लोब हमारे क्षेत्र-व्यापी भारी लॉजिस्टिक्स नेटवर्क को दर्शाता है।',

    // Inquiry Form
    'inq.title': 'सामग्री कोटेशन अनुरोध',
    'inq.subtitle': 'नीचे ऑर्डर विनिर्देश भरें और हमारा मूल्य निर्धारण डेस्क 2 घंटे में दरों का समन्वय करेगा।',
    'inq.name': 'आपका नाम / कंपनी',
    'inq.email': 'ईमेल पता',
    'inq.phone': 'फ़ोन नंबर',
    'inq.division': 'श्रेणी चुनें',
    'inq.div.hotel': 'सीमेंट और टीएमटी स्टील',
    'inq.div.sand': 'रेत और गिट्टी कार्गो',
    'inq.div.materials': 'निर्माण और प्लास्टर आपूर्ति',
    'inq.message': 'आवश्यक मात्रा और वितरण साइट का पता',
    'inq.submit': 'कोटेशन अनुरोध सबमिट करें',
    'inq.sending': 'प्रक्रिया जारी है...',
    'inq.success': 'धन्यवाद! आपका कोटेशन अनुरोध दर्ज कर लिया गया है। हमारी मूल्य निर्धारण टीम जल्द ही आपसे संपर्क करेगी।',
    'inq.error': '⚠️ कुछ गलत हो गया। कृपया विवरण जांचें और पुनः प्रयास करें।',

    // Chatbot
    'chat.welcome': 'नमस्ते! जय श्री राम में आपका स्वागत है। मैं आपका सामग्री सहायक हूँ। आज मैं निर्माण आपूर्ति में आपकी क्या सहायता कर सकता हूँ?',
    'chat.opt.hotel': 'सामग्री मूल्य सूची का अनुरोध करें',
    'chat.opt.sand': 'रेत वितरण कोटेशन प्राप्त करें',
    'chat.opt.materials': 'थोक सीमेंट/स्टील के बारे में पूछें',
    'chat.opt.support': 'रसद डिस्पैचर से संपर्क करें',

    // About Us
    'about.story.title': 'संरचनात्मक अखंडता की विरासत',
    'about.story.desc': 'श्री भय्या पाटिल द्वारा स्थापित, जय श्री राम एक स्थानीय कार्गो पारगमन ऑपरेटर से बढ़कर एक अग्रणी क्षेत्रीय निर्माण सामग्री वितरक बन गया है। हम बड़े गोदामों का संचालन करते हैं जो प्रमुख डेवलपर्स को आपूर्ति करते हैं।',
    'about.vision': 'हमारा दृष्टिकोण',
    'about.vision.desc': 'महाराष्ट्र में बुनियादी ढांचे और आवास परियोजनाओं के लिए सबसे विश्वसनीय, बड़े पैमाने पर संचालित निर्माण सामग्री भागीदार बनना।',
    'about.mission': 'हमारा मिशन',
    'about.mission.desc': 'मजबूत संरचनाओं का समर्थन करते हुए, प्रमाणित, उच्च-टिकाऊ कंक्रीट सामग्री, स्टील और गिट्टी समय पर प्रदान करना।',
    'about.cert': 'इंजीनियरिंग मान्यताएं और मानक',

    // Contact
    'contact.info': 'केंद्रीय कॉर्पोरेट मुख्य कार्यालय',
    'contact.phone': 'थोक प्रेषण डेस्क',
    'contact.email': 'कॉर्पोरेट पूछताछ',
    'contact.address': 'गिरड, तालुका भड़गांव, जिला जलगांव, महाराष्ट्र, भारत',
    'contact.whatsapp': 'सेल्स डेस्क से चैट करें',
  },
  mr: {
    // Nav
    'nav.home': 'मुख्य पृष्ठ',
    'nav.about': 'आमच्याबद्दल',
    'nav.products': 'उत्पादने',
    'nav.services': 'सेवा',
    'nav.projects': 'पूर्ण झालेले प्रकल्प',
    'nav.gallery': 'गॅलरी',
    'nav.quotation': 'कोटेशन',
    'nav.contact': 'संपर्क साधा',
    'nav.admin': 'डॅशबोर्ड',
    'nav.tools': 'स्मार्ट टूल्स',
    'nav.sourcing': 'पुरवठा आणि भागीदार',
    'nav.company': 'कंपनी',
    'nav.estimator': 'खर्च अंदाजक',
    'nav.compare': 'साहित्य तुलना',
    'nav.ai-assistant': 'एआय सहाय्यक',
    'nav.rfq': 'दरपत्रक पोर्टल',
    'nav.marketplace': 'मार्केटप्लेस',
    'nav.partners': 'भागीदार नेटवर्क',
    'nav.seller': 'विक्रेता पोर्टल',
    'nav.estimator.desc': 'घर बांधणी खर्चाचा अंदाज काढा',
    'nav.compare.desc': 'सिमेंट आणि स्टील ब्रँड्सची तुलना करा',
    'nav.ai-assistant.desc': 'एआय बांधकाम सल्लागाराची मदत घ्या',
    'nav.rfq.desc': 'घाऊक ऑर्डरसाठी दरपत्रक मागवा',
    'nav.marketplace.desc': 'बांधकाम साहित्य ऑनलाईन मागवा',
    'nav.partners.desc': 'अधिकृत डीलर आणि इंजिनियर नेटवर्क',
    'nav.seller.desc': 'विक्रेता डॅशबोर्ड आणि व्यवस्थापन',
    'nav.about.desc': 'आमचा प्रवास, ताफा आणि गोदामे',
    'nav.contact.desc': 'थोक पुरवठा डेस्कशी संपर्क साधा',
    'nav.projects.desc': 'पूर्ण झालेल्या प्रकल्पांचे दालन',

    // Hero
    'hero.title': 'प्रीमियम बांधकाम साहित्य आणि पायाभूत सुविधा वितरण',
    'hero.title_part1': 'भविष्याचे निर्माण',
    'hero.title_part2': 'एका वेळी एक साहित्य',
    'hero.subtitle': 'उत्कृष्ट सिमेंट ब्रँड, उच्च-सहनशक्ती टीएमटी स्टील, धुऊन घेतलेली नदीची वाळू, खडी आणि हार्डवेअर साहित्याचे अधिकृत घाऊक पुरवठादार।',
    'hero.cta.portal': 'कॅटलॉग पहा',
    'hero.cta.contact': 'कोटेशन मागवा',
    'hero.scroll_indicator': 'कथा जाणून घेण्यासाठी स्क्रॉल करा',
    'hero.award': 'पुरस्कार प्राप्त सोर्सिंग सोल्युशन्स',

    // Stats
    'stats.clients': 'डीलर नेटवर्क',
    'stats.trips': 'पूर्ण झालेल्या डिलिव्हरी',
    'stats.meals': 'पुरवठा केलेले प्रकल्प',
    'stats.materials': 'टन वितरित',

    // Company Story Timeline
    'story.sub': 'प्रगतीचा इतिहास',
    'story.title': 'आमची 3D बांधकाम टाइमलाइन',
    'story.desc': 'पहा आम्ही पायापासून सुरुवात करून प्रादेशिक स्तरावरील एक अग्रगण्य वितरण नेटवर्क कसे उभारले.',
    'story.m1.title': 'स्थानिक सोर्सिंग बेस',
    'story.m1.desc': 'तीन डंपरच्या लहान ताफ्यासह प्रादेशिक नदीतील वाळू आणि खडी पुरवठा सुरू केला.',
    'story.m2.title': 'वाहतूक ताफ्याचा विस्तार',
    'story.m2.desc': '१५ उच्च क्षमतेचे ट्रान्झिट टिपर खरेदी केले आणि आयएसओ ९००१ प्रमाणित गोदामांचे बांधकाम पूर्ण केले.',
    'story.m3.title': 'घाऊक डीलरशिप',
    'story.m3.desc': 'अल्ट्राटेक सिमेंट, जेएसडब्ल्यू आणि टाटा टिस्कॉन स्टील यांच्याशी थेट डीलरशिपचे करार केले.',
    'story.m4.title': 'पुढील पिढीचे Marketplace',
    'story.m4.desc': 'एआय-चालित बांधकाम खर्च अंदाजक आणि डिजिटल मार्केटप्लेस सोर्सिंग पोर्टल सुरू केले.',

    // Product Showcase
    'prod.sub': 'थेट कारखान्यातून',
    'prod.title': 'उत्पादने दालन (गॅलरी)',
    'prod.desc': '3D मॉडेल पाहण्यासाठी आणि घाऊक दर एक्सप्लोर करण्यासाठी माउस फिरवा.',
    'prod.status': '🟢 लाईव्ह दर निश्चिती सक्रिय',
    'prod.cert_desc': 'अधिकृत प्रयोगशाळा चाचणी आणि हमीयुक्त मजबुतीसह प्रमाणित प्रीमियम दर्जेदार उत्पादने.',
    'prod.specs_label': 'तांत्रिक तपशील',
    'prod.rate_label': 'घाऊक निव्वळ किंमत',
    'prod.btn_market': 'मार्केटप्लेसवर जा',
    'prod.btn_compare': 'साहित्याची तुलना करा',
    'prod.p1.name': 'अल्ट्राटेक ओपीसी ५३ सिमेंट',
    'prod.p1.desc': 'भारी खांब आणि पायांच्या बांधकामासाठी उच्चतम मजबुती देणारे सिमेंट.',
    'prod.p1.spec': '53 MPa संपीड़न मजबुती',
    'prod.p1.rate': '₹३८० - ₹४३० / पोते',
    'prod.p2.name': 'टाटा टिस्कॉन Fe ५५०D स्टील',
    'prod.p2.desc': 'उच्च लवचिकता असलेल्या भूकंपरोधक टीएमटी स्टीलच्या सळ्या.',
    'prod.p2.spec': 'Fe 550D उच्च लवचिकता',
    'prod.p2.rate': '₹६४,००० - ₹६८,००० / मेट्रिक टन',
    'prod.p3.name': 'गिरणा नदीची स्वच्छ वाळू',
    'prod.p3.desc': 'प्लास्टर आणि आरसीसी बांधकामासाठी चिखल विरहित दोनदा धुऊन घेतलेली वाळू.',
    'prod.p3.spec': '<१% गाळाचे प्रमाण',
    'prod.p3.rate': '₹६,५०० / ब्रास',
    'prod.p4.name': 'क्रश केलेली खडी',
    'prod.p4.desc': 'मानक १० मिमी आणि २० मिमी आकारात उच्च घनतेची बेसाल्ट दगडी खडी.',
    'prod.p4.spec': '१००% कठीण बेसाल्ट खडक',
    'prod.p4.rate': '₹४,००० - ₹४,२०0 / ब्रास',
    'prod.p5.name': 'अॅस्ट्रल सीपीव्हीसी / पीव्हीसी पाईप्स',
    'prod.p5.desc': 'गरम/थंड पाण्याचे प्लंबिंग जोडणीसाठी प्रमाणित औद्योगिक दर्जाचे सीपीव्हीसी आणि पीव्हीसी पाईप्स.',
    'prod.p5.spec': 'SDR 11 & SWR प्रमाणित',
    'prod.p5.rate': '₹३५० / मीटर',

    // Logistics Supply Chain
    'log.sub': 'वितरण मार्ग',
    'log.title': 'आमची पुरवठा साखळी प्रवास',
    'log.desc': 'आमच्या पुरवठा डेपोमधून साहित्य थेट तुमच्या बांधकाम साईटपर्यंत कसे पोहोचते ते पहा.',
    'log.s1.title': 'थेट कारखान्यातून सोर्सिंग',
    'log.s1.desc': 'सिमेंट आणि स्टील थेट उत्पादक कारखान्यांतून लोड केले जाते.',
    'log.s1.detail': 'अल्ट्राटेक आणि टाटा भागीदारी',
    'log.s2.title': 'वेब्रीज (धर्मकांटा) तपासणी',
    'log.s2.desc': 'अचूक वजन सुनिश्चित करण्यासाठी डंपर आणि ट्रक्स धर्मकाट्यावर तपासले जातात.',
    'log.s2.detail': 'चिखल विरहित वाळू / शुद्ध मटेरियल',
    'log.s3.title': 'ट्रान्झिट लॉजिस्टिक्स',
    'log.s3.desc': 'महाराष्ट्रातील रस्त्यावरून धावणाऱ्या वाहनांचे रिअल-टाईम जीपीएस ट्रॅकिंग.',
    'log.s3.detail': '२४/७ डंपर ताफा',
    'log.s4.title': 'साईटवर डिलिव्हरी',
    'log.s4.desc': 'डिजिटल बिलासह साहित्य बांधकाम साईटवर अनलोड केले जाते.',
    'log.s4.detail': 'टप्प्याटप्प्याने मोबिलायझेशन',

    // Why Choose Us
    'wcu.sub': 'आमची मानके',
    'wcu.title': 'बांधकाम व्यावसायिक आमच्यावर का विश्वास ठेवतात',
    'wcu.subtitle': 'प्रमाणित कागदपत्रे आणि वेगवान वाहतुकीसह प्रीमियम बांधकाम साहित्याचा पुरवठा.',
    'wcu.quality.title': 'प्रमाणित गुणवत्ता',
    'wcu.quality.desc': 'ओपीसी/पीपीसी सिमेंट आणि Fe 550D टीएमटी स्टील सरळ्यांच्या बॅचेस डिलिव्हरीपूर्वी कठोर प्रयोगशाळा चाचण्यांमधून जातात.',
    'wcu.fleet.title': 'लॉजिस्टिक्स सामर्थ्य',
    'wcu.fleet.desc': 'आमचा स्वतःचा वाहतूक ताफा आणि वाहने २४/७ साईटवर साहित्य पोहोचवण्याची हमी देतात.',
    'wcu.support.title': 'प्रकल्प डेस्क सहाय्य',
    'wcu.support.desc': 'व्यावसायिक गृहनिर्माण प्रकल्पांसाठी टप्प्याटप्प्याने साहित्य पुरवठा करण्याचे नियोजन करणारे समर्पित व्यवस्थापक.',
    'wcu.i1.title': 'प्रमाणित गुणवत्ता',
    'wcu.i1.desc': 'सर्व साहित्य प्रयोगशाळा चाचण्यांमधून जाते. केवळ आयएसआय-प्रमाणित कारखान्यांमधून आणले जाते.',
    'wcu.i2.title': 'लॉजिस्टिक ताकद',
    'wcu.i2.desc': 'डंपर ट्रक्सचा स्वतःचा ताफा २४/७ डिलिव्हरी देतो. जळगाव जिल्ह्यात वेळेत पोहोचवण्याची हमी.',
    'wcu.i3.title': 'घाऊक सूट',
    'wcu.i3.desc': 'थेट कारखान्यांशी असलेले करार आणि दलालांचे कमिशन नसल्यामुळे आम्ही घाऊक दरात सवलत देतो.',
    'wcu.i4.title': 'मोठा साठा (इन्व्हेंटरी)',
    'wcu.i4.desc': 'कोरडी आणि सुरक्षित गोदामांमुळे आमच्याकडे सिमेंट, स्टील आणि वाळू मोठ्या प्रमाणात उपलब्ध असते.',
    'wcu.i5.title': 'तज्ज्ञ सोर्सिंग मदत',
    'wcu.i5.desc': 'टप्प्याटप्प्याने साहित्याचे नियोजन (BOQ) आखून देणारा आणि डिलिव्हरीचे वेळापत्रक सांभाळणारा समर्पित व्यवस्थापक.',
    'wcu.i6.title': 'डिजिटल सोर्सिंग साधने',
    'wcu.i6.desc': 'एकच पोर्टलवर ३डी खर्च कॅल्क्युलेटर, जलद तुलना आणि डिजिटल साईट विश्लेषण साधने उपलब्ध.',

    // Before/After Slider
    'proj.sub': 'प्रकल्प सादरीकरण',
    'proj.title': 'पूर्वी आणि नंतरची तुलना',
    'proj.desc': 'कच्च्या खोदकामाच्या साईट्सपासून ते पूर्ण झालेल्या आलिशान इमारतींपर्यंतचा बदल पाहण्यासाठी हँडल सरकवा.',
    'proj.before.label': 'टप्पा १: पाया (फाउंडेशन)',
    'proj.before.title': 'खोदकाम आणि बेस तयार करणे',
    'proj.before.desc': 'गिरड कॅम्पस आवारात स्लॅब आखणीचे काम',
    'proj.after.label': 'टप्पा ४: पूर्ण झालेले स्ट्रक्चर',
    'proj.after.title': 'आधुनिक साहित्य संकुल',
    'proj.after.desc': 'आयएसओ ९००१ प्रमाणित गोदाम आणि साठा केंद्र',
    'proj.s1.title': 'संरचनात्मक सुरक्षा',
    'proj.s1.sub': 'तपासलेली साहित्याची गुणवत्ता',
    'proj.s2.title': 'बांधकाम साईट्स',
    'proj.s2.sub': 'जळगाव परिसरात साहित्य पुरवठा',
    'proj.s3.title': 'वाहतूक फेऱ्या',
    'proj.s3.sub': 'अखंड लॉजिस्टिक्स पुरवठा',
    'proj.s4.title': 'लॉजिस्टिक्स अपयश',
    'proj.s4.sub': 'शून्य अपयश, हमखास वेळेत डिलिव्हरी',

    // Testimonials
    'test.sub': 'बांधकाम व्यावसायिक अभिप्राय',
    'test.title': 'ग्राहकांची प्रशस्तीपत्रके',
    'test.t1.text': 'आमच्या नुकत्याच हाती घेतलेल्या गृहप्रकल्पासाठी, जय श्री रामने अत्यंत कमी वेळेत ५००० ब्रासपेक्षा जास्त नदीतील वाळूचा पुरवठा केला. त्यांचे डंपर वेळेवर साईटवर पोहोचले.',
    'test.t1.role': 'प्रकल्प संचालक, आरएमडी डेव्हलपर्स',
    'test.t1.project': 'गिरड टाउनशिप फेज-I',
    'test.t2.text': 'जय श्री राम हे उच्च क्षमतेच्या सिमेंट आणि टीएमटी स्टील सळ्यांसाठी आमचे एकमेव पुरवठादार आहेत. त्यांचे घाऊक दर आणि नियोजन अप्रतिम आहे.',
    'test.t2.role': 'एमडी, जळगाव बिल्डकॉन',
    'test.t2.project': 'NH-६ पायाभूत सुविधा बायपास',
    'test.t3.text': 'आम्ही जय श्री राम यांच्याकडून टीएमटी स्टील आणि ओपीसी सिमेंट खरेदी करतो. प्रत्येक बॅचसोबत गुणवत्ता अहवाल दिला जातो.',
    'test.t3.role': 'ठेकेदार, पीडब्ल्यूडी पायाभूत सुविधा',
    'test.t3.project': 'पीडब्ल्यूडी शासकीय शाळा प्रकल्प',

    // Contact
    'contact.sub': 'संपर्क साधा',
    'contact.title': 'साहित्य सोर्सिंग सुरू करा',
    'contact.desc': 'खालील फॉर्म भरा किंवा जळगाव जिल्ह्यातील आमच्या मुख्य गोदामांना भेट द्या.',
    'contact.desk_title': 'कॉर्पोरेट सोर्सिंग डेस्क',
    'contact.desk_desc': 'आमच्या व्यावसायिक dispatch अधिकाऱ्यांशी संपर्क साधा. आम्ही २४ तासांत सिमेंट आणि स्टील पाठवण्याची व्यवस्था करतो.',
    'contact.loc_label': 'मुख्य साठा केंद्र',
    'contact.loc_address': 'गिरड, तालुका भडगाव, जळगाव, महाराष्ट्र',
    'contact.phone_label': 'घाऊक मदत कक्ष',
    'contact.email_label': 'कॉर्पोरेट चौकशी',
    'contact.globe_active': 'इंटरॅक्टिव्ह ग्लोब सक्रिय',
    'contact.globe_desc': 'पार्श्वभूमीतील फिरणारा ३D ग्लोब आमचा राज्यव्यापी वाहतूक ताफा दर्शवतो.',

    // Inquiry Form
    'inq.title': 'बांधकाम साहित्य कोटेशन विनंती',
    'inq.subtitle': 'ऑर्डरचे तपशील खाली भरा आणि आमचे दर निश्चिती केंद्र २ तासांत तुमच्याशी संपर्क साधेल.',
    'inq.name': 'तुमचे नाव / कंपनी',
    'inq.email': 'ईमेल पत्ता',
    'inq.phone': 'फोन नंबर',
    'inq.division': 'श्रेणी निवडा',
    'inq.div.hotel': 'सिमेंट आणि टीएमटी स्टील सरळ्या',
    'inq.div.sand': 'वाळू आणि खडी वाहतूक',
    'inq.div.materials': 'बांधकाम आणि प्लास्टर साहित्य',
    'inq.message': 'आवश्यक प्रमाण आणि डिलिव्हरी साईटचा पत्ता',
    'inq.submit': 'कोटेशन विनंती सबमिट करा',
    'inq.sending': 'प्रक्रिया सुरू आहे...',
    'inq.success': 'धन्यवाद! तुमची कोटेशन विनंती नोंदवली गेली आहे. आमची टीम लवकरच संपर्क करेल.',
    'inq.error': '⚠️ काहीतरी चुकले. कृपया तपशील तपासा आणि पुन्हा प्रयत्न करा.',

    // Chatbot
    'chat.welcome': 'नमस्ते! जय श्री राम मध्ये आपले स्वागत आहे. मी आपला साहित्य सहाय्यक आहे. आज मी बांधकाम साहित्याबाबत आपली काय मदत करू शकतो?',
    'chat.opt.hotel': 'साहित्य दरपत्रक मागवा',
    'chat.opt.sand': 'वाळू डिलिव्हरीचे कोटेशन मिळवा',
    'chat.opt.materials': 'मोठ्या प्रमाणावर सिमेंट/स्टीलची चौकशी करा',
    'chat.opt.support': 'वाहतूक व्यवस्थापकाशी संपर्क साधा',

    // About Us
    'about.story.title': 'संरचनात्मक मजबुतीचा वारसा',
    'about.story.desc': 'श्री भय्या पाटील यांच्या मार्गदर्शनाखाली स्थापित, जय श्री राम स्थानिक वाहतूकदारापासून प्रादेशिक स्तरावरील आघाडीचा बांधकाम साहित्य वितरक बनला आहे. आम्ही मोठ्या गोदामांचे संचालन करतो.',
    'about.vision': 'आमचे ध्येय (व्हिजन)',
    'about.vision.desc': 'महाराष्ट्रातील पायाभूत सुविधा आणि गृहनिर्माण प्रकल्पांसाठी विश्वासार्ह आणि सर्वात मोठा बांधकाम साहित्य पुरवठादार भागीदार बनणे.',
    'about.mission': 'आमचे कार्य (मिशन)',
    'about.mission.desc': 'भक्कम इमारती उभारण्यासाठी प्रमाणित, उच्च दर्जाचे सिमेंट, लोखंड आणि खडी वेळेत पुरवणे.',
    'about.cert': 'अभियांत्रिकी मानके आणि प्रमाणपत्रे',

    // Contact General
    'contact.info': 'मुख्य कॉर्पोरेट कार्यालय',
    'contact.phone': 'घाऊक पुरवठा विभाग',
    'contact.email': 'कॉर्पोरेट चौकशी',
    'contact.address': 'गिरड, तालुका भडगाव, जिल्हा जळगाव, महाराष्ट्र, भारत',
    'contact.whatsapp': 'सेल्स डेस्कशी चॅट करा',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('site-language') as Language;
    if (stored && ['en', 'hi', 'mr'].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('site-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
